<?php

namespace Database\Seeders;
use App\Models\Sales;

use Illuminate\Database\Seeder;

class SalesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sales = [
            [
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '1',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],   
            [
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '2',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '3',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '4',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '5',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            
            [
              
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '6',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '7',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '8',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '9',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],

            [
              
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '10',
                'purchase_qty'         => '5',
                'product_price'        => '238.90',
                'profit'               => '104.50',
                'total'                => '1194.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '1090',
                'total_amount_receipt' => '1194.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100001',
                'order_number'         => '100001',
                'product_id'           => '11',
                'purchase_qty'         => '5',
                'product_price'        => '238.90',
                'profit'               => '104.50',
                'total'                => '1194.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '1090',
                'total_amount_receipt' => '1194.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            //100002
            [
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '1',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],   
            [
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '2',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '3',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '4',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '5',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            
            [
              
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '6',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '7',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '8',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '9',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],

            [
              
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '10',
                'purchase_qty'         => '5',
                'product_price'        => '238.90',
                'profit'               => '104.50',
                'total'                => '1194.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '1090',
                'total_amount_receipt' => '1194.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100002',
                'order_number'         => '100002',
                'product_id'           => '11',
                'purchase_qty'         => '5',
                'product_price'        => '238.90',
                'profit'               => '104.50',
                'total'                => '1194.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '1090',
                'total_amount_receipt' => '1194.50',
                'created_at'           => ("2020-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            //100003
            [
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '1',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],   
            [
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '2',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2021-10-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '3',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2021-09-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '4',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2021-08-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '5',
                'purchase_qty'         => '5',
                'product_price'        => '100.90',
                'profit'               => '34.50',
                'total'                => '504.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '470',
                'total_amount_receipt' => '504.50',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            
            [
              
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '6',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2021-11-02"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '7',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2021-11-02"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '8',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2021-11-04"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '9',
                'purchase_qty'         => '5',
                'product_price'        => '134.10',
                'profit'               => '35.50',
                'total'                => '670.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '635',
                'total_amount_receipt' => '670.50',
                'created_at'           => ("2021-11-05"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],

            [
              
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '10',
                'purchase_qty'         => '5',
                'product_price'        => '238.90',
                'profit'               => '104.50',
                'total'                => '1194.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '1090',
                'total_amount_receipt' => '1194.50',
                'created_at'           => ("2021-11-06"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '100003',
                'order_number'         => '100003',
                'product_id'           => '11',
                'purchase_qty'         => '5',
                'product_price'        => '238.90',
                'profit'               => '104.50',
                'total'                => '1194.50',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '1090',
                'total_amount_receipt' => '1194.50',
                'created_at'           => ("2021-11-07"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            
        ];

        Sales::insert($sales);
    }
}
