<?php

namespace Database\Seeders;
use App\Models\Sales;

use Illuminate\Database\Seeder;

class SalesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sales = [
            //1001
            [
                'salesinvoice_id'      => '1001',
                'order_number'         => '1001',
                'user_id'               => '1',
                'product_id'           => '1',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2021-11-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],   
            [
                'salesinvoice_id'      => '1001',
                'order_number'         => '1001',
                'user_id'               => '1',
                'product_id'           => '2',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2021-11-02"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '1001',
                'order_number'         => '1001',
                'user_id'               => '1',
                'product_id'           => '3',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2021-11-03"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '1001',
                'order_number'         => '1001',
                'user_id'               => '1',
                'product_id'           => '4',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2021-11-04"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '1001',
                'order_number'         => '1001',
                'user_id'               => '1',
                'product_id'           => '5',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2021-11-05"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            
            [
              
                'salesinvoice_id'      => '1001',
                'order_number'         => '1001',
                'user_id'               => '1',
                'product_id'           => '6',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2021-11-06"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '1001',
                'order_number'         => '1001',
                'user_id'               => '1',
                'product_id'           => '7',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2021-11-07"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '1001',
                'order_number'         => '1001',
                'user_id'               => '1',
                'product_id'           => '8',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2021-11-08"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '1001',
                'order_number'         => '1001',
                'user_id'               => '1',
                'product_id'           => '9',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2021-11-09"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],

            [
              
                'salesinvoice_id'      => '1001',
                'order_number'         => '1001',
                'user_id'               => '1',
                'product_id'           => '10',
                'purchase_qty'         => '5',
                'product_price'        => '218',
                'profit'               => '104.50',
                'total'                => '1090',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '985.50',
                'total_amount_receipt' => '1090',
                'created_at'           => ("2021-11-10"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            //1002
            [
                'salesinvoice_id'      => '1002',
                'order_number'         => '1002',
                'user_id'               => '1',
                'product_id'           => '1',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2021-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],   
            [
                'salesinvoice_id'      => '1002',
                'order_number'         => '1002',
                'user_id'               => '1',
                'product_id'           => '2',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2021-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '1002',
                'order_number'         => '1002',
                'user_id'               => '1',
                'product_id'           => '3',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2021-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '1002',
                'order_number'         => '1002',
                'user_id'               => '1',
                'product_id'           => '4',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2021-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '1002',
                'order_number'         => '1002',
                'user_id'               => '1',
                'product_id'           => '5',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2021-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            
            [
              
                'salesinvoice_id'      => '1002',
                'order_number'         => '1002',
                'user_id'               => '1',
                'product_id'           => '6',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2021-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '1002',
                'order_number'         => '1002',
                'user_id'               => '1',
                'product_id'           => '7',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2021-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '1002',
                'order_number'         => '1002',
                'user_id'               => '1',
                'product_id'           => '8',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2021-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
            ],
            [
              
                'salesinvoice_id'      => '1002',
                'order_number'         => '1002',
                'user_id'               => '1',
                'product_id'           => '9',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2021-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],

            [
              
                'salesinvoice_id'      => '1002',
                'order_number'         => '1002',
                'user_id'               => '1',
                'product_id'           => '10',
                'purchase_qty'         => '5',
                'product_price'        => '218',
                'profit'               => '104.50',
                'total'                => '1090',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '985.50',
                'total_amount_receipt' => '1090',
                'created_at'           => ("2021-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            //1003
            [
                'salesinvoice_id'      => '1003',
                'order_number'         => '1003',
                'user_id'               => '1',
                'product_id'           => '1',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2020-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],   
            [
                'salesinvoice_id'      => '1003',
                'order_number'         => '1003',
                'user_id'               => '1',
                'product_id'           => '2',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2020-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '1003',
                'order_number'         => '1003',
                'user_id'               => '1',
                'product_id'           => '3',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2020-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '1003',
                'order_number'         => '1003',
                'user_id'               => '1',
                'product_id'           => '4',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2020-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ], 
            [
              
                'salesinvoice_id'      => '1003',
                'order_number'         => '1003',
                'user_id'               => '1',
                'product_id'           => '5',
                'purchase_qty'         => '5',
                'product_price'        => '94',
                'profit'               => '34.50',
                'total'                => '470',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '435.50',
                'total_amount_receipt' => '470',
                'created_at'           => ("2020-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            
            [
              
                'salesinvoice_id'      => '1003',
                'order_number'         => '1003',
                'user_id'               => '1',
                'product_id'           => '6',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2020-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '1003',
                'order_number'         => '1003',
                'user_id'               => '1',
                'product_id'           => '7',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2020-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '1003',
                'order_number'         => '1003',
                'user_id'               => '1',
                'product_id'           => '8',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2020-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '1003',
                'order_number'         => '1003',
                'user_id'               => '1',
                'product_id'           => '9',
                'purchase_qty'         => '5',
                'product_price'        => '127',
                'profit'               => '35.50',
                'total'                => '635',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '599.50',
                'total_amount_receipt' => '635',
                'created_at'           => ("2020-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
            [
              
                'salesinvoice_id'      => '1003',
                'order_number'         => '1003',
                'user_id'               => '1',
                'product_id'           => '10',
                'purchase_qty'         => '5',
                'product_price'        => '218',
                'profit'               => '104.50',
                'total'                => '1090',
                'status'               => '0',
                'customer_id'          => '1',
                'pricetype_id'         => '1',
                'discounted'           => '0',
                'total_cost'           => '985.50',
                'total_amount_receipt' => '1090',
                'created_at'           => ("2020-12-01"),
                'updated_at'           => date("Y-m-d H:i:s"),
                
            ],
        ];

        Sales::insert($sales);
    }
}
